using System.ComponentModel.DataAnnotations;

namespace WebApplicationDemo
{
    public class Customer
    {
        public int Id { get; set; } //generated by typing "prop" tab, tab

        [Required, StringLength(50)]//Allows the users up to 50 characters
        public string Name { get; set; }
    }
}